import type {
  Tenant,
  User,
  CreditCard,
  BankAccount,
  RecurringExpense,
  Transaction,
} from '@wallet/types'

// ─── Tenant ──────────────────────────────────────────────────────────────────

export const tenant: Tenant = {
  id: 'tenant_portiz',
  name: 'Portiz Family',
  plan: 'family',
  createdAt: '2024-01-15T00:00:00Z',
}

// ─── Users ────────────────────────────────────────────────────────────────────

export const users: User[] = [
  {
    id: 'user_juan',
    tenantId: 'tenant_portiz',
    name: 'Juan Portiz',
    email: 'jp@calaps.com',
    role: 'owner',
    familyRole: 'parent',
    avatarColor: '#7c3aed',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user_maria',
    tenantId: 'tenant_portiz',
    name: 'Maria Portiz',
    email: 'maria@calaps.com',
    role: 'admin',
    familyRole: 'partner',
    avatarColor: '#db2777',
    createdAt: '2024-01-16T00:00:00Z',
  },
  {
    id: 'user_kobe',
    tenantId: 'tenant_portiz',
    name: 'Kobe Portiz',
    email: 'kobe@calaps.com',
    role: 'viewer',
    familyRole: 'child',
    avatarColor: '#0891b2',
    createdAt: '2024-02-01T00:00:00Z',
  },
]

export const currentUser = users[0]

// ─── Credit Cards ─────────────────────────────────────────────────────────────

export const creditCards: CreditCard[] = [
  {
    id: 'card_amex_platinum',
    tenantId: 'tenant_portiz',
    ownerId: 'user_juan',
    name: 'Amex Platinum',
    lastFour: '4242',
    network: 'amex',
    creditLimit: { amount: 50_000, currency: 'MXN' },
    usedCredit: { amount: 11_480, currency: 'MXN' },
    statementDate: 5,
    dueDate: 20,
    isShared: false,
    sharedWith: [],
    gradient: ['#7c3aed', '#db2777'],
    color: '#7c3aed',
  },
  {
    id: 'card_bbva_azul',
    tenantId: 'tenant_portiz',
    ownerId: 'user_juan',
    name: 'BBVA Azul',
    lastFour: '8891',
    network: 'visa',
    creditLimit: { amount: 30_000, currency: 'MXN' },
    usedCredit: { amount: 21_350, currency: 'MXN' },
    statementDate: 12,
    dueDate: 27,
    isShared: true,
    sharedWith: [
      { userId: 'user_maria', permission: 'edit' },
      { userId: 'user_kobe', permission: 'view' },
    ],
    gradient: ['#0891b2', '#4f46e5'],
    color: '#0891b2',
  },
  {
    id: 'card_bi_mastercard',
    tenantId: 'tenant_portiz',
    ownerId: 'user_juan',
    name: 'BI Mastercard',
    lastFour: '3317',
    network: 'mastercard',
    creditLimit: { amount: 15_000, currency: 'GTQ' },
    usedCredit: { amount: 2_800, currency: 'GTQ' },
    statementDate: 1,
    dueDate: 15,
    isShared: false,
    sharedWith: [],
    gradient: ['#059669', '#0891b2'],
    color: '#059669',
  },
  {
    id: 'card_promerica_platinum',
    tenantId: 'tenant_portiz',
    ownerId: 'user_juan',
    name: 'Promerica Platinum',
    lastFour: '6609',
    network: 'visa',
    creditLimit: { amount: 12_000, currency: 'USD' },
    usedCredit: { amount: 1_940, currency: 'USD' },
    statementDate: 8,
    dueDate: 22,
    isShared: false,
    sharedWith: [],
    gradient: ['#b45309', '#d97706'],
    color: '#b45309',
  },
]

// ─── Bank Accounts ────────────────────────────────────────────────────────────

export const bankAccounts: BankAccount[] = [
  {
    id: 'acct_cash',
    tenantId: 'tenant_portiz',
    ownerId: 'user_juan',
    bank: 'other',
    country: 'MX',
    name: 'Cash',
    lastFour: '0000',
    balance: { amount: 4_200, currency: 'MXN' },
    type: 'checking',
  },
  {
    id: 'acct_bbva_mx_checking',
    tenantId: 'tenant_portiz',
    ownerId: 'user_juan',
    bank: 'BBVA',
    country: 'MX',
    name: 'BBVA',
    lastFour: '2210',
    balance: { amount: 173_320, currency: 'MXN' },
    type: 'checking',
  },
  {
    id: 'acct_bbva_mx_savings',
    tenantId: 'tenant_portiz',
    ownerId: 'user_juan',
    bank: 'BBVA',
    country: 'MX',
    name: 'BBVA Ahorro',
    lastFour: '5543',
    balance: { amount: 125_000, currency: 'MXN' },
    type: 'savings',
  },
  {
    id: 'acct_bi_gt_checking',
    tenantId: 'tenant_portiz',
    ownerId: 'user_juan',
    bank: 'BI',
    country: 'GT',
    name: 'BI Quetzales',
    lastFour: '7788',
    balance: { amount: 18_450, currency: 'GTQ' },
    type: 'checking',
  },
  {
    id: 'acct_bi_gt_usd',
    tenantId: 'tenant_portiz',
    ownerId: 'user_juan',
    bank: 'BI',
    country: 'GT',
    name: 'BI Dólares',
    lastFour: '4421',
    balance: { amount: 3_850, currency: 'USD' },
    type: 'checking',
  },
]

// ─── Recurring Expenses ───────────────────────────────────────────────────────

export const recurringExpenses: RecurringExpense[] = [
  {
    id: 'rec_kobe_support',
    tenantId: 'tenant_portiz',
    name: 'Kobe Support',
    amount: { amount: 2_000, currency: 'GTQ' },
    frequency: 'monthly',
    nextDate: '2026-07-01T00:00:00Z',
    category: 'Family',
    recipient: 'Kobe Portiz',
    icon: '👨‍👦',
  },
  {
    id: 'rec_netflix',
    tenantId: 'tenant_portiz',
    name: 'Netflix',
    amount: { amount: 199, currency: 'MXN' },
    frequency: 'monthly',
    nextDate: '2026-06-15T00:00:00Z',
    category: 'Entertainment',
    icon: '🎬',
    linkedAccountId: 'card_bbva_azul',
  },
  {
    id: 'rec_spotify',
    tenantId: 'tenant_portiz',
    name: 'Spotify Family',
    amount: { amount: 129, currency: 'MXN' },
    frequency: 'monthly',
    nextDate: '2026-06-18T00:00:00Z',
    category: 'Entertainment',
    icon: '🎵',
    linkedAccountId: 'card_amex_platinum',
  },
  {
    id: 'rec_aws',
    tenantId: 'tenant_portiz',
    name: 'AWS',
    amount: { amount: 45, currency: 'USD' },
    frequency: 'monthly',
    nextDate: '2026-06-28T00:00:00Z',
    category: 'Technology',
    icon: '☁️',
    linkedAccountId: 'card_amex_platinum',
  },
  {
    id: 'rec_gym',
    tenantId: 'tenant_portiz',
    name: 'Gym Membership',
    amount: { amount: 800, currency: 'MXN' },
    frequency: 'monthly',
    nextDate: '2026-06-20T00:00:00Z',
    category: 'Health',
    icon: '🏋️',
    linkedAccountId: 'card_bbva_azul',
  },
  {
    id: 'rec_rent',
    tenantId: 'tenant_portiz',
    name: 'Renta',
    amount: { amount: 18_000, currency: 'MXN' },
    frequency: 'monthly',
    nextDate: '2026-07-01T00:00:00Z',
    category: 'Housing',
    icon: '🏠',
    linkedAccountId: 'acct_bbva_mx_checking',
  },
  {
    id: 'rec_internet',
    tenantId: 'tenant_portiz',
    name: 'Megacable Internet',
    amount: { amount: 499, currency: 'MXN' },
    frequency: 'monthly',
    nextDate: '2026-06-22T00:00:00Z',
    category: 'Utilities',
    icon: '📡',
    linkedAccountId: 'card_bbva_azul',
  },
]

// ─── Recent Transactions ──────────────────────────────────────────────────────

export const recentTransactions: Transaction[] = [
  {
    id: 'tx_001',
    accountId: 'card_amex_platinum',
    amount: { amount: 1_250, currency: 'MXN' },
    description: 'Restaurante Pujol',
    date: '2026-06-08T21:30:00Z',
    category: 'Dining',
    type: 'debit',
    merchant: 'Pujol',
  },
  {
    id: 'tx_002',
    accountId: 'card_bbva_azul',
    amount: { amount: 3_800, currency: 'MXN' },
    description: 'Liverpool — Ropa',
    date: '2026-06-07T15:20:00Z',
    category: 'Shopping',
    type: 'debit',
    merchant: 'Liverpool',
  },
  {
    id: 'tx_003',
    accountId: 'acct_bbva_mx_checking',
    amount: { amount: 55_000, currency: 'MXN' },
    description: 'Nómina Junio',
    date: '2026-06-05T08:00:00Z',
    category: 'Income',
    type: 'credit',
  },
  {
    id: 'tx_004',
    accountId: 'card_bi_mastercard',
    amount: { amount: 450, currency: 'GTQ' },
    description: 'Supermercado La Torre',
    date: '2026-06-04T12:00:00Z',
    category: 'Groceries',
    type: 'debit',
    merchant: 'La Torre',
  },
  {
    id: 'tx_005',
    accountId: 'card_amex_platinum',
    amount: { amount: 199, currency: 'MXN' },
    description: 'Netflix',
    date: '2026-06-03T00:00:00Z',
    category: 'Entertainment',
    type: 'debit',
    merchant: 'Netflix',
  },
  {
    id: 'tx_006',
    accountId: 'acct_bbva_mx_savings',
    amount: { amount: 5_000, currency: 'MXN' },
    description: 'Transferencia a Ahorro',
    date: '2026-06-02T10:30:00Z',
    category: 'Transfer',
    type: 'credit',
  },
  {
    id: 'tx_007',
    accountId: 'card_bbva_azul',
    amount: { amount: 2_100, currency: 'MXN' },
    description: 'Uber Rides — Semana',
    date: '2026-06-01T18:00:00Z',
    category: 'Transport',
    type: 'debit',
    merchant: 'Uber',
  },
  {
    id: 'tx_008',
    accountId: 'card_amex_platinum',
    amount: { amount: 4_500, currency: 'MXN' },
    description: 'Apple Store',
    date: '2026-05-30T14:00:00Z',
    category: 'Technology',
    type: 'debit',
    merchant: 'Apple',
  },
  {
    id: 'tx_009',
    accountId: 'acct_bbva_mx_checking',
    amount: { amount: 18_000, currency: 'MXN' },
    description: 'Renta Mayo',
    date: '2026-05-28T09:00:00Z',
    category: 'Housing',
    type: 'debit',
  },
  {
    id: 'tx_010',
    accountId: 'card_bbva_azul',
    amount: { amount: 650, currency: 'MXN' },
    description: 'Farmacia del Ahorro',
    date: '2026-05-27T16:45:00Z',
    category: 'Health',
    type: 'debit',
    merchant: 'Farmacia del Ahorro',
  },
  {
    id: 'tx_011',
    accountId: 'acct_bi_gt_checking',
    amount: { amount: 2_000, currency: 'GTQ' },
    description: 'Kobe Support — Mayo',
    date: '2026-05-26T10:00:00Z',
    category: 'Family',
    type: 'debit',
  },
  {
    id: 'tx_012',
    accountId: 'card_amex_platinum',
    amount: { amount: 799, currency: 'MXN' },
    description: 'Cinépolis — Avengers',
    date: '2026-05-24T20:00:00Z',
    category: 'Entertainment',
    type: 'debit',
    merchant: 'Cinépolis',
  },
  {
    id: 'tx_013',
    accountId: 'acct_bbva_mx_checking',
    amount: { amount: 55_000, currency: 'MXN' },
    description: 'Nómina Mayo',
    date: '2026-05-05T08:00:00Z',
    category: 'Income',
    type: 'credit',
  },
  {
    id: 'tx_014',
    accountId: 'card_bbva_azul',
    amount: { amount: 3_200, currency: 'MXN' },
    description: 'El Puerto de Liverpool',
    date: '2026-05-20T13:30:00Z',
    category: 'Shopping',
    type: 'debit',
    merchant: 'Liverpool',
  },
  {
    id: 'tx_015',
    accountId: 'card_bi_mastercard',
    amount: { amount: 890, currency: 'GTQ' },
    description: 'Despensa Familiar',
    date: '2026-05-18T11:00:00Z',
    category: 'Groceries',
    type: 'debit',
    merchant: 'Despensa Familiar',
  },
  {
    id: 'tx_016',
    accountId: 'card_promerica_platinum',
    amount: { amount: 320, currency: 'USD' },
    description: 'Delta Airlines',
    date: '2026-05-15T07:30:00Z',
    category: 'Transport',
    type: 'debit',
    merchant: 'Delta Airlines',
  },
  {
    id: 'tx_017',
    accountId: 'acct_bi_gt_usd',
    amount: { amount: 1_500, currency: 'USD' },
    description: 'Wire Transfer — Freelance',
    date: '2026-05-12T14:00:00Z',
    category: 'Income',
    type: 'credit',
  },
  {
    id: 'tx_018',
    accountId: 'card_amex_platinum',
    amount: { amount: 2_400, currency: 'MXN' },
    description: 'Costco — Despensa',
    date: '2026-05-10T10:00:00Z',
    category: 'Groceries',
    type: 'debit',
    merchant: 'Costco',
  },
  {
    id: 'tx_019',
    accountId: 'card_bbva_azul',
    amount: { amount: 499, currency: 'MXN' },
    description: 'Megacable Internet',
    date: '2026-05-08T00:00:00Z',
    category: 'Utilities',
    type: 'debit',
    merchant: 'Megacable',
  },
  {
    id: 'tx_020',
    accountId: 'card_amex_platinum',
    amount: { amount: 129, currency: 'MXN' },
    description: 'Spotify Family',
    date: '2026-05-04T00:00:00Z',
    category: 'Entertainment',
    type: 'debit',
    merchant: 'Spotify',
  },
]

// Helper: account display name for a transaction accountId
export function accountLabel(accountId: string): string {
  const card = creditCards.find((c) => c.id === accountId)
  if (card) return `${card.name} ••••${card.lastFour}`
  const bank = bankAccounts.find((a) => a.id === accountId)
  if (bank) return `${bank.name} ••••${bank.lastFour}`
  return accountId
}

// ─── Spending by Category (for charts) ────────────────────────────────────────

export const spendingByCategory = [
  { name: 'Housing', value: 18_000, color: '#7c3aed' },
  { name: 'Food & Dining', value: 6_200, color: '#db2777' },
  { name: 'Shopping', value: 8_900, color: '#0891b2' },
  { name: 'Transport', value: 2_100, color: '#059669' },
  { name: 'Entertainment', value: 1_127, color: '#d97706' },
  { name: 'Technology', value: 5_345, color: '#6366f1' },
  { name: 'Health', value: 800, color: '#10b981' },
  { name: 'Family', value: 3_900, color: '#f59e0b' },
]

export type MonthRow = { month: string; MXN: number; GTQ: number; USD: number }

export const monthlySpending: MonthRow[] = [
  { month: 'Jan', MXN: 38_200, GTQ: 4_100, USD: 220 },
  { month: 'Feb', MXN: 42_100, GTQ: 3_800, USD: 180 },
  { month: 'Mar', MXN: 35_400, GTQ: 5_200, USD: 310 },
  { month: 'Apr', MXN: 51_000, GTQ: 3_600, USD: 245 },
  { month: 'May', MXN: 44_700, GTQ: 4_900, USD: 195 },
  { month: 'Jun', MXN: 29_850, GTQ: 2_800, USD: 90 },
]

// Multi-year monthly spending data for period comparisons
export const allYearsSpending: Record<number, MonthRow[]> = {
  2024: [
    { month: 'Jan', MXN: 29_100, GTQ: 3_000, USD: 140 },
    { month: 'Feb', MXN: 33_400, GTQ: 3_100, USD: 130 },
    { month: 'Mar', MXN: 27_800, GTQ: 4_000, USD: 200 },
    { month: 'Apr', MXN: 41_200, GTQ: 2_800, USD: 180 },
    { month: 'May', MXN: 36_500, GTQ: 3_700, USD: 160 },
    { month: 'Jun', MXN: 24_100, GTQ: 2_200, USD: 75 },
    { month: 'Jul', MXN: 38_900, GTQ: 4_300, USD: 210 },
    { month: 'Aug', MXN: 35_200, GTQ: 3_900, USD: 190 },
    { month: 'Sep', MXN: 31_700, GTQ: 3_500, USD: 170 },
    { month: 'Oct', MXN: 44_800, GTQ: 4_600, USD: 230 },
    { month: 'Nov', MXN: 52_300, GTQ: 5_100, USD: 280 },
    { month: 'Dec', MXN: 61_400, GTQ: 5_800, USD: 320 },
  ],
  2025: [
    { month: 'Jan', MXN: 33_500, GTQ: 3_600, USD: 185 },
    { month: 'Feb', MXN: 37_800, GTQ: 3_400, USD: 160 },
    { month: 'Mar', MXN: 31_100, GTQ: 4_700, USD: 270 },
    { month: 'Apr', MXN: 46_300, GTQ: 3_200, USD: 215 },
    { month: 'May', MXN: 40_100, GTQ: 4_400, USD: 175 },
    { month: 'Jun', MXN: 26_500, GTQ: 2_500, USD: 82 },
    { month: 'Jul', MXN: 43_700, GTQ: 4_800, USD: 235 },
    { month: 'Aug', MXN: 39_400, GTQ: 4_200, USD: 210 },
    { month: 'Sep', MXN: 35_100, GTQ: 3_900, USD: 195 },
    { month: 'Oct', MXN: 49_200, GTQ: 5_000, USD: 250 },
    { month: 'Nov', MXN: 57_800, GTQ: 5_600, USD: 305 },
    { month: 'Dec', MXN: 68_100, GTQ: 6_300, USD: 355 },
  ],
  2026: [
    { month: 'Jan', MXN: 38_200, GTQ: 4_100, USD: 220 },
    { month: 'Feb', MXN: 42_100, GTQ: 3_800, USD: 180 },
    { month: 'Mar', MXN: 35_400, GTQ: 5_200, USD: 310 },
    { month: 'Apr', MXN: 51_000, GTQ: 3_600, USD: 245 },
    { month: 'May', MXN: 44_700, GTQ: 4_900, USD: 195 },
    { month: 'Jun', MXN: 29_850, GTQ: 2_800, USD: 90 },
  ],
}

export const MONTH_NAMES = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
export const CURRENT_YEAR = 2026
export const CURRENT_MONTH = 5 // 0-indexed, June
